### PR TITLE
use chronic gem for more robust date parsing

### LINKED ISSUE #4: Make date handling more robust
Right now we if `Date.parse` fails, so do we. Analyze common patterns and see if we can account for them and/or ask (someone?) to get them fixed.

### PR DESCRIPTION
**Pull request by tampakis**
Closes #4.
I'm going to rebase #6 to include the enhancements there minus the date parsing code.

### CODE REVIEW

**Comment by tampakis** [comment]
Also rebased.

File: lib/orangetheses.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 require 'orangetheses/version'
 
 module Orangetheses
-  SET = 'hdl_88435_dsp019c67wm88m'
+  SET = 'com_88435_dsp019c67wm88m'
```
Comment (jpstroop) [inline lib/orangetheses.rb]: Did the set ID change?

Comment (tampakis) [inline lib/orangetheses.rb]: yeah it did: http://dataspace.princeton.edu/oai/request?verb=ListIdentifiers&metadataPrefix=oai_dc&set=com_88435_dsp019c67wm88m
